runs:
  using: "composite"

  steps:

  - name: configure
    shell: bash
    run: >-
      cmake
      --preset default
      -Dparallel:BOOL=${{ matrix.parallel }}
      -Dscotch:BOOL=${{ matrix.scotch }}
      -Dmetis:BOOL=${{ matrix.metis }}
      -DLAPACK_VENDOR=${{ matrix.lapack_vendor }}

  - name: build, test release
    shell: bash
    run: cmake --workflow --preset default

  - name: install package
    shell: bash
    run: cmake --install build
