name: ci

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CTEST_NO_TESTS_ACTION: error
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  CTEST_PARALLEL_LEVEL: 0
  CMAKE_INSTALL_PREFIX: ~/local
  CMAKE_PREFIX_PATH: ~/local
  CMAKE_GENERATOR: Ninja

on:
  push:
    paths:
      - "**.c"
      - "**.f"
      - "**.F"
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**.cmake.in"
      - "**.txt"
      - ".github/workflows/ci.yml"
      - "!scripts/*"

jobs:

  core:
    timeout-minutes: 15

    strategy:
      matrix:
        scotch: [false]
        metis: [false]
        parallel: [true]
        lapack_vendor: [""]
        os: [ubuntu-24.04, macos-latest]
        include:
          - scotch: true
            os: ubuntu-24.04
          - metis: true
            os: ubuntu-24.04
          - lapack_vendor: "OpenBLAS"
            os: ubuntu-24.04
          - parallel: false
            os: ubuntu-24.04

    runs-on: ${{ matrix.os }}

    env:
      FC: gfortran-13

    steps:

    - uses: actions/checkout@v4

    - name: install prereqs
      uses: ./.github/workflows/composite-deps

    - name: build and install
      uses: ./.github/workflows/composite-build

    - name: build example
      uses: ./.github/workflows/composite-example
